export enum CardsActionTypes {
  SET_CARDS_DECK = "SET_CARDS_DECK",
  CLICK_ON_CARD = "CLICK_ON_CARD",
  SET_STATUS_TWO_CARDS = "SET_STATUS_TWO_CARDS",
  ADD_COMPARE_CARD = "ADD_COMPARE_CARD",
  CLEAR_COMPARE_CARD = "CLEAR_COMPARE_CARD",
  RESTART_GAME = "RESTART_GAME",
  CLOSE_CARDS = "CLOSE_CARDS",
}
