export enum CardsActionTypes {
  CLICK_ON_CARD = "CLICK_ON_CARD",
  SET_STATUS_TWO_CARDS = "SET_STATUS_TWO_CARDS",
  ADD_COMPARE_CARD = "ADD_COMPARE_CARD",
  CLEAR_COMPARE_CARD = "CLEAR_COMPARE_CARD",
}
