export enum SettingsActionTypes {
  SHOW_SETTINGS = "SHOW_SETTINGS",
  HIDE_SETTINGS = "HIDE_SETTINGS",
  SET_MUSIC = "SET_MUSIC",
  SET_SOUND = "SET_SOUND",
  SET_ARENA = "SET_ARENA",
  SET_BOARD = "SET_BOARD",
  SET_WRAPPER_CARD = "SET_WRAPPER_CARD",
  SET_DIFFICULT = "SET_DIFFICULT",
}
